[#2]: align python project conf with corporate convention, extend:
+ add file header, order sections alphabetically, replace " by ',
  add classifiers, description, license; reset version to 0.0.0
+ NOTE: attempting to create a venv at this stage fails with
  $ (cd code/python && uv sync)
      ... (python exception leaked by uv omitted) ...
  ValueError: Unable to determine which files to ship
  inside the wheel using the following heuristics:
  https://hatch.pypa.io/latest/plugins/ ...
   ... builder/wheel/#default-file-selection

  The most likely cause of this is that there is no directory that
  matches the name of your project (keyring_insecure_backend).

  At least one file selection option must be defined
  in the `tool.hatch.build.targets.wheel` table,
  see: https://hatch.pypa.io/latest/config/build/

  As an example, if you intend to ship a directory named `foo` that
  resides within a `src` directory located at the root of your project,
  you can define the following:

  [tool.hatch.build.targets.wheel]
  packages = ["src/foo"]

  hint: This usually indicates a problem
  with the package or the build environment.